### ISSUE TITLE
Drop support for ruby 1.8

### ISSUE THREAD

**Issue by nextmat** [librato/librato-metrics#101]
Trying to balance dependencies between newer and older versions of ruby along w/ jruby, ree etc has become increasingly difficult. I'm inclined to cut a v2.0 which drops support for anything before the 1.9 syntax (REE, MRI 1.8, jruby 1.8 mode etc).

Any thoughts / strong opinions? @obfuscurity @jderrett @mheffner @josephruscio

**Comment by brodock** [comment]
Please do it... your gem has an aging faraday dependency because of Ruby 1.8...

**Comment by nextmat** [comment]
@brodock Thanks for the heads up on the faraday dep.

**Comment by nextmat** [comment]
Just opened #110 to start documenting next steps for a v2.0, this is included there.

**Comment by chancefeick** [comment]
Resolved in #119.
