### ISSUE TITLE
Support a default source for measurements

### ISSUE THREAD

**Issue by jderrett** [librato/librato-metrics#106]
We received a request to "Have an option to set default source in the Librato::Metrics.authenticate call".

Maybe this could look something like:
`Librato::Metrics.default_source = 'foo'`

somewhat similar to the default source behavior in `aggregator = Librato::Metrics::Aggregator.new(:source => 'foobar')`

**Comment by nextmat** [comment]
You can already do:

```ruby
queue = Librato::Metrics::Queue.new(source: 'mysource')
queue.add a_metric: 123, another_metric: 345
queue.submit
```

I can kind of see the value in setting something that is a default for any generated queue or aggregator, but it isn't too difficult to set it on instantiation?

**Comment by jderrett** [comment]
Agreed, closing this.
