### ISSUE TITLE
Road to 2.0

### ISSUE THREAD

**Issue by nextmat** [librato/librato-metrics#110]
Our dependencies are getting creaky and some parts of this gem are long in the tooth so I wanted to go ahead and put together a list of what I think we need to do to transition to a solid 2.0

- [x] Remove support for ruby 1.8 / REE
- [x] Ensure support for ruby 2.2
- [x] Remove support for deprecated versions of methods
- [x] Unlock faraday version dependency (possible once we don't need to support 1.8)
- [x] Don't require multijson as a hard dependency, only use if present (otherwise use stdlib json)
- [x] Upgrade rspec stack to modern versions / conventions (expect, etc)

**Comment by obfuscurity** [comment]
Yup, I'm getting the notifications anyways. :heart:

**Comment by chancefeick** [comment]
Resolved in #120.
