### ISSUE TITLE
What is jruby-openssl needed for?

### ISSUE THREAD

**Issue by jjb** [librato/librato-metrics#111]
I've been running on jruby for years and haven't needed it. Why does this gem need it?

**Comment by nextmat** [comment]
It may be that it is no longer needed in jruby. At the time that we added support there was no SSL support built into jruby.

I'd be happy to drop the dependency if this is no longer needed. I don't have a jruby env handy to verify, would appreciate thoughts from anyone else on jruby.

**Comment by nextmat** [comment]
Going to go ahead and close this, if any jruby folks run into issues let us know and we'll re-evaluate.
